<a href="https://colab.research.google.com/github/christy726/NumPY_101/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Initializing NumPy***



In [39]:
import numpy as np
import time

In [4]:
a=np.zeros((6,2))
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((5,4))
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], a shape = (6, 2), a data type = float64
np.zeros(4) :   a = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], a shape = (5, 4), a data type = float64


In [5]:
a=np.random.random_sample((2,4))
print(f"np.random.random_sample(2,4)  : a = {a}, \n a shape ={a.shape}, a data type = {a.dtype}")

np.random.random_sample(2,4)  : a = [[0.79542062 0.51060846 0.51399004 0.31153278]
 [0.67195845 0.72269399 0.07056135 0.56140853]], 
 a shape =(2, 4), a data type = float64


In [6]:
a=np.arange((4))
print(f"np.arange(4) : a ={a} a shape ={a.shape}, a data typetype = {a.dtype}")

a=np.random.rand(5)
print(a)

np.arange(4) : a =[0 1 2 3] a shape =(4,), a data typetype = int64
[0.68731926 0.69402812 0.41616656 0.24426965 0.70640909]


In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"np.arange(4) : a ={a} a shape ={a.shape}, a data typetype = {a.dtype}")

np.arange(4) : a =[[1 2 3]
 [4 5 6]
 [7 8 9]] a shape =(3, 3), a data typetype = int64


**Operations on vectors**

In [8]:
#indexing_of_a_Vector

a=np.arange(10)
print(f"a[2].shape = {a[2].shape}, a[2] = {a[2]}")

try:
  c=a[10]
except Exception as e:
  print("The error mesage you eill see is : ")
  print(e)


a[2].shape = (), a[2] = 2
The error mesage you eill see is : 
index 10 is out of bounds for axis 0 with size 10


In [ ]:
a=np.arange(10)
print(f"a         = {a}")

c=a[1:9:2]
print(c)

c = a[3:];
print("a[3:]    = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
a[3:]    =  [3 4 5 6 7 8 9]


In [ ]:
a = np.arange(10)
print(f"a         = {a}")

c=a[2:7:1];
print(f"a[2:7:1] = {a[2:7:1]}")

c=a[3:];
print(f"a[3:] = {a[3:]}")

c=a[:3];
print(f"a[:3] = {a[:3]}")

c=a[:]
print(f"a[:] = {a[:]}")

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.array([1,2,3,4])
print(f"a          : {a}")

b=-a
print(f"b=-a = {b}")


b=np.sum(a)
print(f"np.sum(a) = {b}")

b=np.mean(a)
print(f"np.means(a) = {b}")

b=a**2
print(f"a**2 = {b}")

a          : [1 2 3 4]
b=-a = [-1 -2 -3 -4]
np.sum(a) = 10
np.means(a) = 2.5
a**2 = [ 1  4  9 16]


In [ ]:
a=np.array([1,2,4])
b=np.array([-1,-2,3,4])
#print(f"the sum is {a+b}")

try:
  c=a+b
except Exception as e:
  print("The error message you'll see is:")
  print(e)


The error message you'll see is:
operands could not be broadcast together with shapes (3,) (4,) 


In [ ]:
a=np.array([1,2,3,4])
b=a*5
print(f"b=a*5 = {b}")

b=a*5 = [ 5 10 15 20]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([2,4,1,3])
c=np.dot(a,b)
print(f"NumPy 1-D np.dot(a,b) ={c}, np.dot(a,b) = {c.shape}")
c=np.dot(b,a)
print(f"NumPy 1-D np.dot(a,b) ={c}, np.dot(a,b) = {c.shape}")

NumPy 1-D np.dot(a,b) =25, np.dot(a,b) = ()
NumPy 1-D np.dot(a,b) =25, np.dot(a,b) = ()


In [ ]:
def my_dot(a, b):
    """
   Compute the dot product of two vectors

    Args:
      a (ndarray (n,)):  input vector
      b (ndarray (n,)):  input vector with same dimension as a

    Returns:
      x (scalar):
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x


# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [ ]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 12.9411 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 3559.9139 ms 


In [9]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


In [24]:
a=np.zeros((1,5))
print(f"a shape = {a.shape}, a = {a}")

a=np.zeros((2,1))
print(f'a shape = {a.shape}, a = {a}')

a = np.random.random_sample((1, 1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.34795856]]


In [26]:
a = np.array([[5], [4], [3]])
print(f" a shape = {a.shape}, np.array: a = {a}")

a = np.array([[5],
              [4],
              [3]]);
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [46]:
a=np.arange(6).reshape(-1,2)
print(f"a.shape: {a.shape}, \na= {a}")
#print("\n",a[2])
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

print(f"\na[2].shape = {a[2].shape}, a[2] = {a[2]}, ")
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar


a[2].shape = (2,), a[2] = [4 5], 
a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


In [65]:
a=np.arange(20).reshape(-1,10)
print(f"a = \n{a}")

print(f"a[0, 2:7:1] = {a[0, 2:7:1]}, a[0, 2:7:1].shape = {a[0, 2:7:1].shape}")

print(f"a[:, 2:7:1] = {a[:, 2:7:1]}, a[0, 2:7:1].shape = {a[:, 2:7:1].shape}")

print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] = [2 3 4 5 6], a[0, 2:7:1].shape = (5,)
a[:, 2:7:1] = [[ 2  3  4  5  6]
 [12 13 14 15 16]], a[0, 2:7:1].shape = (2, 5)
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
